name: Keep Heroku app running

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    name: Trigger app
    runs-on: ubuntu-latest
    steps:
      - name: make request
        run: curl https://salty-woodland-30436.herokuapp.com/